export const Cashiers=[
    {
        cashierId:1,
        name:'Juan',
        clients:[
            {
                transactionId:1,
                schedule:9,
                totalTransactions:1,
                totalAmount:5000
            },
            {
                transactionId:2,
                schedule:5,
                totalTransactions:2,
                totalAmount:1000
            },
        ]
    },
    {
        cashierId:2,
        name:'David',
        clients:[
            {
                transactionId:3,
                schedule:10,
                totalTransactions:4,
                totalAmount:8000
            },
            {
                transactionId:4,
                schedule:3,
                totalTransactions:2,
                totalAmount:2000
            },
            {
                transactionId:5,
                schedule:3,
                totalTransactions:1,
                totalAmount:2000
            },
        ]
    }
]